### ISSUE TITLE
brew install is not working

### ISSUE THREAD

**Issue by msound** [devinci-code/ahoy#28]
I ran the command:
```
brew tap devinci-code/tap
```
and it ran successfully.

The next command gives me an error:
```
--- ~ » brew install ahoy
Error: undefined method `desc' for Formulary::Formulae::Ahoy:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/devinci-code/homebrew-tap/ahoy.rb:2:in `<class:Ahoy>'
/usr/local/Library/Taps/devinci-code/homebrew-tap/ahoy.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by frankcarey** [comment]
huh, we just set this up for 2 new developers on a few different OSX versions and it worked fine for them.

What version of homebrew and ruby are you running? This is what I have.

```
$ brew --version
Homebrew 0.9.9 (git revision 01e8e; last commit 2016-06-16)
Homebrew/homebrew-core (git revision 8913; last commit 2016-06-16)

$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
```
